ALTER TABLE accounts ADD COLUMN contact_email TEXT NOT NULL DEFAULT '';
ALTER TABLE accounts ADD COLUMN phone TEXT NOT NULL DEFAULT '';
ALTER TABLE accounts ADD COLUMN address_line1 TEXT NOT NULL DEFAULT '';
ALTER TABLE accounts ADD COLUMN address_line2 TEXT NOT NULL DEFAULT '';
ALTER TABLE accounts ADD COLUMN city TEXT NOT NULL DEFAULT '';
ALTER TABLE accounts ADD COLUMN state TEXT NOT NULL DEFAULT '';
ALTER TABLE accounts ADD COLUMN postal_code TEXT NOT NULL DEFAULT '';
ALTER TABLE accounts ADD COLUMN country TEXT NOT NULL DEFAULT '';
