ALTER TABLE accounts DROP COLUMN IF EXISTS country;
ALTER TABLE accounts DROP COLUMN IF EXISTS postal_code;
ALTER TABLE accounts DROP COLUMN IF EXISTS state;
ALTER TABLE accounts DROP COLUMN IF EXISTS city;
ALTER TABLE accounts DROP COLUMN IF EXISTS address_line2;
ALTER TABLE accounts DROP COLUMN IF EXISTS address_line1;
ALTER TABLE accounts DROP COLUMN IF EXISTS phone;
ALTER TABLE accounts DROP COLUMN IF EXISTS contact_email;
